### ISSUE TITLE
Hide auto mode feature is not working

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#132]
I’m using ataDisableAutoMode = true but my expectation was for this option to remove the auto option from the HK heatercooler drop-down menu.

**Comment by grzegorz914** [comment]
You can try 2.3.0 beta. 
## Changes

- removed from config.json `ataDisableAutoMode`, `ataDisableHeatMode`, `ataAutoHeatMode`
- added to config.json `ataHeatDryFanMode`, `ataCoolDryFanMode`, `ataAutoDryFanMode`
- cleanup
- config schema updated

In this upcoming version I have added possibility to configure individual mode for `HEAT`, `COOL` and `AUTO` inclusive disable it. We have only one problem if disable some function because Homa app doesn't allow to remove the `AUTO`, `COOL`  or `HEAT` option from the HK heater/cooler drop-down menu.

**Comment by grzegorz914** [comment]
2.3.0 released

- unfortunatelly disabled operating mode cannot be hiden in HomeKit app due to HomeKit app limitations
